#!/bin/bash

###############################################################################
#############
####		VARIABLE DEFINITION
#############
###############################################################################

#get full path to working directory, kvm tends to have problem accessing
# disk images when they are defined by relative path
WORKINGDIR=`pwd`
DATADIR=$WORKINGDIR/data

# make all commands visible
UPDATEBASE=0
CREATEBASE=0
INSTALLIPA=0
SETREPO=0

# file name format: f15-ipa-demo-base.date.qcow2
# file with new image
IMGNAME="f15-ipa-demo-base"
TEMPORARYIMAGE="$WORKINGDIR/ipa-working-image.qcow2"
INSTALLIMAGE="$WORKINGDIR/ipa-ready-image.qcow2"

# file with base image
BASEIMAGE=""

# kickstart files for server and clients
KSSERVER=f15-freeipa-base.ks

# kickstart file
KSFILE=$DATADIR/f15-freeipa-base.ks.temp

# filename of ssh keys that will be generated by script
SSHKEY_NAME=sshipademo
SSHKEY_FOLDER=$WORKINGDIR/cert
SSHKEY_FILENAME=""
# name of user to be created on all of the VMs
USERNAME=ipademo

# ssh settings for override asking for confirmation when adding ssh key
# THIS OPTION IS VERY INSECURE AND SHOULDN'T BE USED FOR NONDEMONSTRATIVE PURPOSES
SSHOPT="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# configuration data necessary for installation
VMNAME=f15-ipa-base

# number of cpu's used by virtual machine
VCPU=1
# availible ram ( 1 gb = 1048576 )
VRAM=1048576
# ARCHitecture
ARCH=x86_64
# fedora os version
OSVERSION=15
# disk size
DISKSIZE=10

# fedora repository
OSREPOSITORY=http://download.fedoraproject.org/pub/fedora/linux/releases/$OSVERSION/Fedora/$ARCH/os
#OSREPOSITORY=http://download.englab.brq.redhat.com/pub/fedora/linux/releases/$OSVERSION/Fedora/$ARCH/os

# name of directory containing ARCHIVEd base images
ARCHIVE=archive


###############################################################################
#############
####		FUNCTIONS DEFINITION
#############
###############################################################################

# function to get ip address of VM
# $1 - name of VM
function getVmIp ()
{
	macaddr=`virsh dumpxml $1 | grep "mac address" | awk -F\' '{print $2}'`
	
	ipaddr=`arp -an | grep $macaddr`

	while [ -z "$ipaddr" ]; do
		sleep 10
		ipaddr=`arp -an | grep $macaddr | awk '{print $2}'`
	done
	
	ipaddr=`echo ${ipaddr%?} | cut -c2-`
	
	echo $ipaddr
}

# function for detecting when the VM is running and ready to execute commands
# $1 - VM's ip address
# $2 - certificate location
function waitForStart ()
{
	flag=255
	while [ ! $flag -eq 0 ]; do
		sleep 10
		ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $2 root@$1 'exit' &> /dev/null
		flag=$?
	done
}

# function for waiting untill the VM is shutdown correctly
# $1 - VM name
function waitForEnd ()
{
	while [ -z "`virsh list --inactive | grep $1`" ]; do
		sleep 10
	done
}

# function to check whether variable really contains number
# first parametr - variable to check
function isNumber {
	if [ -z `echo $1 | grep "^[0-9]*$"` ]
	then
		return 1;
	else
		return 0;
	fi
}

# function that prints help
# $1 - repository address
function printHelp {
	echo "Ipa-base-prepare script"
	echo "This script should help you prepare base images to allow you create virtual machines that are ready for FreeIPA installation."
	echo "ATTENTION: You must have libvirt, qemu, qemu-kvm, qemu-img, qemu-system, python-virtinst, openssh-clients installed to run the script correctly."
	echo "usage: ipa-base-prepare.sh [--createbase | --updatebase | --installipa][--repo repoaddr][--sshkey pathtokey][--archive archdir][-h | --help]"
	echo "Mandatory arguments:"
	echo "--repo - set fedora repository, by default it's: $1"
	echo "ATTENTION: You must use nearest repository, because the default one is overloaded. Mirrors list is here: http://mirrors.fedoraproject.org/publiclist/Fedora/15/x86_64/"
	echo "--createbase - create base image"
	echo "--updatebase - update base image"
	echo "--installipa - prepare installation image - take actual base image and install freeipa-server with all dependencies into it"
	echo ""
	echo "Optional arguments:"
	echo "-h, --help - print help"
	echo "--base - specify one base image  - if you want to use base images that is older or located in different directory then the archive."
	echo "--archive - specify directory containing base images"
	echo "--sshkey - specify private ssh key to be used. It's supposed that public key has the same name with \'.pub\' suffix. The key will be used for connecting to VMs."
}

# function to get PID - get PID of process which handles virtual machine installation
# first argument - name of virtual machine
function getVirtInstPid {
	ps -eo pid,args | grep -v grep | grep "$1" | head -1 | awk '{ print $1}'
}

# function to wait for completion of installation of virtual machine
# first argument - name of virtual machine currently installed
function waitForInst {
	while [ ! -z `getVirtInstPid $1` ]; do
		sleep 30
	done
}

# function to generate ssh keys to allow file operations over scp
# $1 - name of key
# $2 - log file
# passphrase is empty
function createSshCert {
	if [ -f $1 ]
	then
		rm -f $1
		rm -f $1.pub
	fi

	ssh-keygen -t rsa -f $1 -N '' -C "ipademo" &>> $2
	if [ ! $? -eq 0 ]
	then
		echo "Unable to generate SSH key!" &>> $2
		exit 1
	fi
}

#function for preparing image and installing virtual machine
# $1 - directory to store images
# $2 - name of machine
# $3 - kickstart file
# $4 - os repository
# $5 - disk size
# $6 - log file

function virtInstall {
	
	#prepare image for ipa-server
	qemu-img create -f qcow2 -o preallocation=metadata "$1" "$5"G &>> $6
	
	if [ ! $? -eq 0 ]
	then
		echo "Can not create virtual image!"
		exit 1
	fi
	
	#install ipa-server vm
	virt-install --connect=qemu:///system \
	    --initrd-inject="$3" \
	    --name="$2" \
	    --extra-args="ks=file:/$3 \
	      console=tty0 console=ttyS0,115200" \
	    --location="$4" \
	    --disk path="$1",format=qcow2 \
	    --ram 1024 \
	    --vcpus=2 \
	    --check-cpu \
	    --accelerate \
	    --hvm \
	    --vnc \
	    --os-type=linux \
	    --noautoconsole &>> $LOGFILE

# with this option the program won't work on rhel
# 	    --os-variant=fedora15 \

	if [ ! $? -eq 0 ]
	then
		echo "Unable to create virtual machine!"
		virsh undefine $2
		rm -rf $1
		rm -rf $3
		exit 1
	fi
}

# function for editing kickstartfile
# first param - template
# second param - output file
# third param - user name
function prepareKickstart {
	tempfile=tmp
	pkgs=`cat $1 | awk '{if($1=="%packages") print NR}'`
	lines=`cat $1 | wc -l`
	lines=$(($lines-$pkgs))
	head -$pkgs $1 > $tempfile
	echo "" >> $tempfile
	tail -$lines $1 >> $tempfile

	lines=`cat $tempfile | wc -l`
	lines=$(($lines-2))
	head -$lines $tempfile > $2
	
	# install all ipa dependencies except ds, pki a freeipa pkgs
	# bind must be added manually since it's not in ipa dependencies
	echo "yum -y install --nogpgcheck --enablerepo=updates-testing bind bind-dyndb-ldap" >> $2
	# get ipa dependencies
	echo "yum -y install --nogpgcheck --enablerepo=updates-testing \`yum deplist freeipa-server | grep -v pki | grep -v freeipa | grep -v dogtag | grep -v 389-ds | grep -v / | grep -v \".*\.so.*\" | grep \"dependency:\" | awk '{print \$2}' | awk -F\( '{print \$1}' | uniq -u | tr '\n' ' '\`" >> $2
	
	echo "cd /root/" >> $2
	echo "mkdir --mode=700 .ssh" >> $2
	echo "echo \"`cat $4.pub`\">>.ssh/authorized_keys" >> $2
	echo "chmod 600 .ssh/authorized_keys" >> $2
	
	echo "" >> $2
	# delete requiretty from /etc/sudoers
	echo "mv /etc/sudoers /etc/sudoers_old" >> $2
	echo "cat /etc/sudoers_old | grep -v requiretty > /etc/sudoers" >> $2
	echo "chmod 440 /etc/sudoers" >> $2
	# add user to sudoer list so that he can use sudo without password
	echo "echo \"%ipausers       ALL = NOPASSWD: ALL\" >> /etc/sudoers" >> $2
	# Various authenticaion config changes
	# Fix SELinux context on the newly created authorized_keys file
	echo "restorecon /root/.ssh/authorized_keys" >> $2
	# close the post section
	tail -2 $tempfile >> $2
	
	#cleanUp
	rm -f $tempfile
}

# function to prepare xml file for virt-image to rerun
# $1 - xml file name
# $2 - vm name
# $3 - relative path to disk image
# $4 - VCPU's number
# $5 - memory
# $6 - ARCHitecture
function virtImageXml ()
{
	diskformat=`qemu-img info $3 | grep "file format" | awk '{print $3}'`
	output=$2.xml
	
	(
	printf "<image>\n"
	printf "\t<name>$2</name>\n"
	
	printf "\t<domain>\n"
	
	printf "\t  <boot type=\"hvm\">\n"
	
	printf "\t    <guest>\n"
	printf "\t\t<arch>$6</arch>\n"
	printf "\t    </guest>\n"
	
	printf "\t    <os>\n"
	printf "\t\t<loader dev=\"hd\"/>\n"
	printf "\t    </os>\n"
	
	printf "\t    <drive disk=\"$3\" target=\"hda\"/>\n"
	printf "\t  </boot>\n"
	
	printf "\t  <devices>\n"
	
	printf "\t\t <vcpu>$4</vcpu>\n"
    printf "\t\t <memory>$5</memory>\n"
    printf "\t\t <interface/>\n"
    printf "\t\t <graphics/>\n"
    
	printf "\t </devices>\n"
	
	printf "\t</domain>\n"
	
	# storage setting
	printf "\t<storage>\n"
	printf "\t\t<disk file=\"$3\" format=\"$diskformat\"/>\n"
	printf "\t</storage>\n"
	printf "</image>\n"
	) > $output
	
}

# function to check whether the user is root
function checkRoot ()
{
	if [ `id -u` -ne 0 ]
	then
		echo "Please run as 'root' to execute '$0'!"
		exit 1
    fi
}

# function for cleaning up messy files
function cleanUp ()
{
	while [ ! -z $1 ]; do
		rm -f $1 &>> $LOGFILE
		shift
	done
}

# function clean virtual machines
function cleanVMs ()
{
	while [ ! -z $1 ]; do
		if [ ! -z "`virsh list --all | grep $1`" ]
		then
				if [ ! -z "`virsh list | grep $1`" ]
				then
					virsh destroy $1 &>> $LOGFILE
				fi
				virsh undefine $1 &>> $LOGFILE
		fi
		shift
	done
}

# function for getting current date
function getDate ()
{
	date +%y%m%d%H%M
}

# function to find last VM
# $1 - date of actual image
# $2 - folder with image ARCHIVE
# $3 - first part of image name, examp. "f15-ipa-base-image"
function getLastImage()
{
	difference=$1
	for i in `ls $2 | grep $3`; do
		imgdate=`echo $i | awk -F\. '{print $2}'`
		tmp=$(($1 - $imgdate))
		if [ $tmp -lt $difference ]
		then
			difference=$tmp
			result=$imgdate
		fi
	done
	
	if [ $difference -eq $1 ]
	then
		echo ""
	else
		echo "$IMGNAME.$result.qcow2"	
	fi
}

# cuts off last backslach in directory address - just to make it compatible
# $1 - address to be checked
function lastCharInPath()
{
	if [ "${1: -1}" == "/" ]
	then
		echo ${1%?}
	else
		echo $1
	fi
}

# function for checking whether the provided path is a web address
checkForWebAddress ()
{
	http=`echo $1 | grep "^http[s]\{0,1\}://[a-zA-Z0-9]\{1,\}"`
	ftp=`echo $1 | grep \"^ftp://[a-zA-Z0-9]\{1,\}\"`
	
	if [ -z "$http" -a -z "$ftp" ]
	then
		return 0
	else
		return 1
	fi
	return 0
}

#################################################################################
####################
########		END OF FUNCTIONS DEFINITION
####################
#################################################################################

# log files
LOGFILE=ipa-base-prepare-`getDate`.log

############
# Add header to log file for current task
echo "" &>> $LOGFILE
echo "NEW RECORD, date:`getDate`" &>> $LOGFILE
echo "" &>> $LOGFILE

echo "Welcome to IPA-BASE-PREPARE script for automatic creating and updating of base images."

# Check whether user is root
checkRoot

#############################################
########## DEALING WITH PARAMETERS
#############################################

# parse arguments
while [ ! -z $1 ]; do
	case $1 in
	--createbase) CREATEBASE=1
			;;
	--updatebase) UPDATEBASE=1
			;;
	--installipa) INSTALLIPA=1
			;;
	--base) if [ -z $2 ]
	    then
		echo "You must specify base image file!"
		exit 1
	    fi
	    BASEIMAGE=$2
		shift
		;;
		
	--archive) if [ -z $2 ]
				then
					echo "You must specify ARCHIVE directory!"
					exit 1
				fi
				ARCHIVE=$2
				shift
				;;
				
	--sshkey) 
				if [ -z $2 ]
				then
					echo "You must specify the ssh key!"
					exit 1
				fi
				SSHKEY_FILENAME=$2
				shift
				;;

	--repo) OSREPOSITORY=$2
		if [ -z $2 ]
		then
			echo "You must specify the repository!"
			exit 1
		fi
		SETREPO=1
		shift
		;;
		
	-h) printHelp $OSREPOSITORY
		exit 0
		;;
		
	--help) printHelp $OSREPOSITORY
			exit 0
		;;
		
	*) echo "Unknown parameter $1"
	    exit 1
		;;
	esac
	shift
done

# check arguments
if [ ! -f $KSFILE ]
then
	echo "Kickstart file for ipa-server missing!" >&2
	exit 1
fi

if [ -z $OSREPOSITORY ]
then
	echo "You must specify address of Fedora repository!" >&2
	exit 1
fi

if [ $SETREPO -eq 0 -a $CREATEBASE -eq 1 ]
then
	echo "Please choose the nearest repository to your location from mirror list: http://mirrors.fedoraproject.org/publiclist/Fedora/15/x86_64/" >&2
	echo "The address must point to '.../x86_64/os' directory, for example: 'http://dl.fedoraproject.org/pub/fedora/linux/releases/15/Fedora/x86_64/os/'" >&2
	exit 1
fi

if [ ! $(($CREATEBASE + $UPDATEBASE + $INSTALLIPA)) -eq 1 ]
then
		echo "You must select only one operation!" >&2
		exit 1
fi

if [ ! -d $DATADIR ]
then
	echo "Directory 'data' with necessary scripts is missing!" >&2
	exit 1
fi

###############################################
########## END OF ARGUMENTS
###############################################

###############################################
#########
####	Preparing images and install scripts
#########
###############################################

IMGFILE=$IMGNAME.`getDate`.qcow2

if [ $CREATEBASE -eq 1 ]
then
	echo "Creating base image:"
	if [ -z $IMGFILE ]
	then
		echo "Image file wasn't specified" >&2
		exit 1
	fi

	printf "\t[1/6] Creating/checking directory for saving base images\n"
	# create folder for achivation of base images and set it as readable for everyone
	if [ ! -d $ARCHIVE ]
	then
		mkdir $ARCHIVE
	fi

	chmod a+r $ARCHIVE
	
	# create new SSH key or check existence of the specified one
	if [ -z "$SSHKEY_FILENAME" ]
	then
		printf "\t[2/6] Creating SSH key\n"
		# create folder for saving certificate
		SSHKEY_FOLDER=`lastCharInPath $SSHKEY_FOLDER`
		
		if [ -d $SSHKEY_FOLDER ]
		then
			echo "Folder $SSHKEY_FOLDER already exists! Please specify another folder for storing SSH keys!" >&2
			exit 1
		else 
			mkdir $SSHKEY_FOLDER
		fi

		SSHKEY_FILENAME=$SSHKEY_FOLDER/$SSHKEY_NAME

		# create ssh cert in specified folder with specified name
		createSshCert $SSHKEY_FILENAME $LOGFILE
		
		# set folder with all containg certificates as readable
		chmod -R 600 $SSHKEY_FOLDER
	else
		printf "\t[2/6] Loading SSH key\n"
		if [ ! -f $SSHKEY_FILENAME ]
		then
			echo "Specified SSH key doesn't exist!" >&2
			exit 1
		fi
	fi

	printf "\t[3/6] Preparing kickstart file\n"
	prepareKickstart $KSFILE $KSSERVER $USERNAME $SSHKEY_FILENAME
	
	echo "Kickstart file for ipa-base machine:" >> $LOGFILE
	cat $KSSERVER >> $LOGFILE

	printf "\t[4/6] Creating virtual machine. This action can take several minutes!\n"
	virtInstall $TEMPORARYIMAGE $VMNAME $KSSERVER $OSREPOSITORY $DISKSIZE $LOGFILE

	waitForInst $VMNAME
	
	printf "\t[5/6] Saving image in ARCHIVE\n"
	mv $TEMPORARYIMAGE $ARCHIVE/$IMGFILE
	
	printf "\t[6/6] Cleaning up\n"
	virsh undefine $VMNAME &>> $LOGFILE
		
	cleanUp $KSSERVER
	echo "Finished! New base image is saved in $ARCHIVE/$IMGFILE !"
else
	#
	# Update of base image or installation of freeipa-server
	#
	
	CURRENTDATE=`getDate`
	
	NEWBASEIMAGE=$IMGNAME.$CURRENTDATE.qcow2
	
	# create folder for saving certificate
	SSHKEY_FOLDER=`lastCharInPath $SSHKEY_FOLDER`
	
	printf "\t[1/9] Loading SSH key\n"
	if [ -z "$SSHKEY_FILENAME" ]
	then		
		SSHKEY_FILENAME=$SSHKEY_FOLDER/$SSHKEY_NAME
	else
		checkForWebAddress $SSHKEY_FILENAME
		if [ $? -eq 1 ]
		then
			wget $SSHKEY_FILENAME -O $WORKINGDIR/$SSHKEY_NAME
			if [ ! $? -eq 0 ]
			then
				echo "Certificate $SSHKEY_FILENAME can't be downloaded!" >&2
			fi
			SSHKEY_FILENAME=$WORKINGDIR/$SSHKEY_NAME
		fi
	fi
	# check existence of SSH key
	if [ ! -f $SSHKEY_FILENAME ]
	then
		echo "Certificate $SSHKEY_FILENAME doesn't exist!" >&2
		exit 1
	fi
	
	printf "\t[2/9] Preparing working image\n"
	# prepare image for ipa-server
	if [ -z $BASEIMAGE ]
	then
		# check existence of ARCHIVE folder
		if [ ! -d $ARCHIVE ]
		then
			echo "Folder $ARCHIVE doesn't exist!" >&2
			exit 1
		fi
		if [ -z "`getLastImage $CURRENTDATE $ARCHIVE $IMGNAME`" ]
		then
			echo "No base images found!" >&2
			exit 1
		fi
		
		qemu-img create -b $ARCHIVE/`getLastImage $CURRENTDATE $ARCHIVE $IMGNAME` -f qcow2 "$TEMPORARYIMAGE" &>> $LOGFILE
	else
		qemu-img create -b $BASEIMAGE -f qcow2 "$TEMPORARYIMAGE" &>> $LOGFILE
	fi
	
	if [ ! $? -eq 0 ]
	then
		echo "Unable to create working copy of base image!" >&2
		rm -f $TEMPORARYIMAGE
		exit 1
	fi
	
	printf "\t[3/9] Preparing definition file for creating virtual machine\n"
	# prepare xml definition of VM that will be used to run system update
	virtImageXml $VMNAME.xml $VMNAME $TEMPORARYIMAGE $VCPU $VRAM $ARCH
	
	printf "\t[4/9] Creating virtual machine\n"
	# start VM defined by XML file
	virt-image $VMNAME.xml &>> $LOGFILE
	
	if [ ! $? -eq 0 ]
	then
		echo "Unable to create VM! Check log file: $LOGFILE" >&2
		cleanVMs $VMNAME
		cleanUp $VMNAME.xml $TEMPORARYIMAGE
		exit 1
	fi
	
	rm -f $VMNAME.xml
	
	# get the machine ip
	printf "\t[5/9] Starting virtual machine\n"
	MACHINEIP=`getVmIp $VMNAME`
	
	waitForStart $MACHINEIP $SSHKEY_FILENAME $LOGFILE
	
	# update system
	printf "\t[6/9] Updating virtual machine's system\n"
	ssh $SSHOPT -i $SSHKEY_FILENAME root@$MACHINEIP 'yum update -y' &>> $LOGFILE
	if [ ! $? -eq 0 ]
	then
		echo "Can not connect to VM." >&2
		cleanVMs $VMNAME
		exit 1
	fi
	
	# if installation of freeipa-server was chosen
	if [ $INSTALLIPA -eq 1 ]
	then
		NEWBASEIMAGE=$INSTALLIMAGE
		printf "\t\tInstalling freeipa-server. This can take several minutes\n"
		ssh $SSHOPT -i $SSHKEY_FILENAME root@$MACHINEIP 'yum install -y --enablerepo=updates-testing freeipa-server' &>> $LOGFILE
		if [ ! $? -eq 0 ]
		then
			echo "Freeipa-server installation failed." >&2
			cleanVMs $VMNAME
			cleanUp $TEMPORARYIMAGE
			exit 1
		fi
	fi
	
	printf "\t[7/9] Shuting down the VM\n"
	ssh $SSHOPT -i $SSHKEY_FILENAME root@$MACHINEIP 'shutdown' &>> $LOGFILE
	
	waitForEnd $VMNAME
	
	printf "\t[8/9] Saving new base image\n"
	qemu-img convert $TEMPORARYIMAGE -O qcow2 $NEWBASEIMAGE &>> $LOGFILE
	
	if [ ! $? -eq 0 ]
	then
		echo "Unable to save base image!" >&2
		cleanVMs $VMNAME
		cleanUp $NEWBASEIMAGE $TEMPORARYIMAGE
		exit 1
	fi
	
	printf "\t[9/9] Cleaning up\n"
	# clean VM used for preparing the machine and also temporary image
	virsh undefine $VMNAME &>> $LOGFILE
	cleanUp $TEMPORARYIMAGE
	
	if [ $UPDATEBASE -eq 1 ]
	then
		if [ -z $BASEIMAGE ]
		then
			mv $NEWBASEIMAGE $ARCHIVE/$NEWBASEIMAGE
			echo "Finished: New base image is saved in $ARCHIVE/$NEWBASEIMAGE"
		else
			echo "Finished: New base image is saved in `pwd`/$NEWBASEIMAGE"
		fi		
	else
		echo "Finished: Base image for installation is ready in $NEWBASEIMAGE"
	fi
fi

exit 0
